import type { Tender } from "./types"

export const mockTenders: Tender[] = [
  {
    id: "1",
    lotNumber: "001",
    name: "Поставка строительных материалов для ЖК Аквамарин",
    initialPrice: 5420000,
    category: "materials",
    procedure: "auction",
    region: "ulyanovsk",
    date: "2025-11-15",
    deliveryPeriod: {
      start: "2025-11-01",
      end: "2026-07-01",
    },
    fillDate: new Date().toISOString().split("T")[0],
    endDate: "2025-10-31T16:00:00",
    items: [
      {
        id: "1",
        name: "Комплекс работ по изготовлению, поставке, монтажу наружных витражей и дверей из алюминиевого профиля",
        unit: "компл.",
        quantity: 1,
      },
    ],
  },
  {
    id: "2",
    lotNumber: "002",
    name: "Подрядные работы по благоустройству территории",
    initialPrice: 12350000,
    category: "contracting",
    procedure: "request_for_proposals",
    region: "moscow",
    date: "2025-11-20",
    deliveryPeriod: {
      start: "2025-11-01",
      end: "2026-07-01",
    },
    fillDate: new Date().toISOString().split("T")[0],
    endDate: "2025-10-31T16:00:00",
    items: [
      {
        id: "1",
        name: "Благоустройство территории жилого комплекса",
        unit: "компл.",
        quantity: 1,
      },
      {
        id: "2",
        name: "Установка малых архитектурных форм",
        unit: "шт",
        quantity: 15,
      },
    ],
  },
  {
    id: "3",
    lotNumber: "003",
    name: "Поставка отделочных материалов",
    initialPrice: 3200000,
    category: "materials",
    procedure: "auction",
    region: "volgograd",
    date: "2025-11-18",
    deliveryPeriod: {
      start: "2025-11-01",
      end: "2026-07-01",
    },
    fillDate: new Date().toISOString().split("T")[0],
    endDate: "2025-10-31T16:00:00",
    items: [
      {
        id: "1",
        name: "Отделочные материалы для внутренних работ",
        unit: "компл.",
        quantity: 1,
      },
    ],
  },
  {
    id: "4",
    lotNumber: "004",
    name: "Строительство инженерных сетей",
    initialPrice: 18900000,
    category: "contracting",
    procedure: "auction",
    region: "bashkortostan",
    date: "2025-11-25",
    deliveryPeriod: {
      start: "2025-11-01",
      end: "2026-07-01",
    },
    fillDate: new Date().toISOString().split("T")[0],
    endDate: "2025-10-31T16:00:00",
    items: [
      {
        id: "1",
        name: "Прокладка инженерных коммуникаций",
        unit: "компл.",
        quantity: 1,
      },
    ],
  },
  {
    id: "5",
    lotNumber: "005",
    name: "Поставка сантехнического оборудования",
    initialPrice: 4100000,
    category: "materials",
    procedure: "request_for_proposals",
    region: "khabarovsk",
    date: "2025-11-22",
    deliveryPeriod: {
      start: "2025-11-01",
      end: "2026-07-01",
    },
    fillDate: new Date().toISOString().split("T")[0],
    endDate: "2025-10-31T16:00:00",
    items: [
      {
        id: "1",
        name: "Сантехническое оборудование",
        unit: "шт",
        quantity: 50,
      },
    ],
  },
  {
    id: "6",
    lotNumber: "006",
    name: "Фасадные работы жилого комплекса",
    initialPrice: 9800000,
    category: "contracting",
    procedure: "auction",
    region: "lipetsk",
    date: "2025-11-28",
    deliveryPeriod: {
      start: "2025-11-01",
      end: "2026-07-01",
    },
    fillDate: new Date().toISOString().split("T")[0],
    endDate: "2025-10-31T16:00:00",
    items: [
      {
        id: "1",
        name: "Фасадные работы",
        unit: "компл.",
        quantity: 1,
      },
    ],
  },
]
